// import { jsonToSchema } from "@/lib/jsontoschema";
import fs from 'fs'
// import { jsonToSchema } from 'nextql_schema'
// const jsonText = fs.readFileSync('./test/test.txt').toString()
// console.log(JSON.parse(jsonText))
import { jsonToTC,jsonToSchema } from 'nextql_schema'

const JSObj = {
  hello:"world"
}

const JSObjs = [JSObj,JSObj]

const JSONOBJ = {
  "hello":"world"
}

const JSONSTR = `{"testing":"1"}`

const json = 
{
  "id": "1",
  "parent": "__SOURCE__",
  "internal": {
    "type": "Post",
    "sha": "76b5b013abdfb648e774ae80b5375025fc375337c83137dae9ab72742b82c4c7"
  },
  "children": [
    ['1','2']
  ],
  "title": "testingPurpose",
  "content": "",
  "tags": null,
  "dates": [
    "2022-02-27T13:03:00Z",
    "2022-02-27T13:00:04Z",
    "2022-02-27T12:59:53Z",
    "2022-02-24T16:12:01Z"
  ]
}


// console.log(typeof JSONSTR)

// if(typeof test1 === 'object'){
// const test3 = JSON.parse(JSONSTR)

// }
// console.log(test);
// console.log(JSON.parse(test));

const result = jsonToTC({baseType:'AutogeneratedMainType',prefix:'',jsonInput:json})
// const result = jsonToSchema({baseType:'AutogeneratedMainType',prefix:'',jsonInput:json})

// console.log(result);
console.log(result);