// import { jsonToSchema } from "@/lib/jsontoschema";
// import fs from 'fs'
// const jsonText = fs.readFileSync('./test/test.txt').toString()
// // console.log(JSON.parse(jsonText))

// const result = jsonToSchema({baseType:'AutogeneratedMainType',prefix:'',jsonInput:JSON.parse(jsonText)})

// console.log(result);