import { jsonToSchema } from "@/lib/jsontoschema";
import fs from 'fs'
// const jsonText = fs.readFileSync('./test/test.txt').toString()
// console.log(JSON.parse(jsonText))

const JSObj = {
  hello:"world"
}

const JSObjs = [JSObj,JSObj]

const JSONOBJ = {
  "hello":"world"
}

const JSONSTR = `{"testing":"1"}`

// console.log(typeof JSONSTR)

// if(typeof test1 === 'object'){
// const test3 = JSON.parse(JSONSTR)

// }
// console.log(test);
// console.log(JSON.parse(test));

const result = jsonToSchema({baseType:'AutogeneratedMainType',prefix:'',jsonInput:JSObjs})

console.log(result);